name: Test
on:
  push:
jobs:
  cuda:
    name: CUDA py${{ matrix.python }}
    runs-on: [self-hosted, cuda, python]
    defaults: {run: {shell: 'bash -el {0}'}}
    strategy:
      matrix:
        python: [3.13]
    steps:
    - uses: actions/checkout@v6
      with: {fetch-depth: 0}
    - name: Run setup-python
      # cupy!=14.0 https://github.com/cupy/cupy/issues/9777
      # cuda-cudart-dev https://github.com/cupy/cupy/issues/9962
      run: setup-python -p${{ matrix.python }} cupy"!=14.0.*" cuda-cudart-dev
    - name: debug info
      run: |
        echo $PATH
        echo $LD_LIBRARY_PATH
        #eval "$CONDA_CI_ACTIVATE"
        #echo $PATH
        #echo $LD_LIBRARY_PATH
        which python
        which pip
        python -c "import cupy; cupy.show_config(_full=True)"
    - name: pip install -U -e .[dev]
      run: |
        eval "$CONDA_CI_ACTIVATE"
        make CXX_FLAGS='' deps-build build-editable deps-run
    - run: make test
    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Post Run setup-python
      run: setup-python -p${{ matrix.python }} -Dr
      if: ${{ always() }}
